### ISSUE TITLE
Could you please upload code of reformatting data into mne type

### ISSUE THREAD

**Issue by Kang1121** [SPOClab-ca/ThinkerInvariance#2]

**Comment by Kang1121** [comment]
you used transformed dataset, but didn't provide the detail how you transform

**Comment by Kang1121** [comment]
As you experiment with different datasets, each of which had gone through different preprocessing procedures, it's quite difficult to know how to build a new dataset which could fit well with the network.

Could you please simply explain what should be done in the raw data preprocessing part?

Thanks!

**Comment by Kang1121** [comment]
As for the dataset Competition IV, I did it myself, and share the code below for anyone who is interested in this code. Thanks.


```
import scipy.io as scio
import os
import mne


# Because original Competition IV test file split
# their data and labels, I need to put them together here
label_path = 'D:/true_labels/'
file_path = 'Z:/BCI-Competition-IV/2a/mne_ready/'


for file in os.listdir(label_path):
    name = file.split('.')[0]
    label = scio.loadmat(os.path.join(label_path, file))['classlabel']
    data = mne.io.read_raw_gdf(os.path.join(file_path, name + '.gdf'))

    # replace true labels with unknown label '783'
    temp = data.annotations.description
    count = 0
    for i in range(len(temp)):
        if temp[i] == '783':
            temp[i] = label[count][0]
            count += 1
    data.annotations.description = temp

    data.save(file_path + name + '.raw.fif', overwrite=True)
```

**Comment by Kang1121** [comment]
`import scipy.io as scio
import os
import mne


# Because original Competition IV test file split
# their data and labels, I need to put them together here
label_path = 'D:/true_labels/'
file_path = 'Z:/BCI-Competition-IV/2a/mne_ready/'


for file in os.listdir(label_path):
    name = file.split('.')[0]
    label = scio.loadmat(os.path.join(label_path, file))['classlabel']
    data = mne.io.read_raw_gdf(os.path.join(file_path, name + '.gdf'))

    # replace true labels with unknown label '783'
    temp = data.annotations.description
    count = 0
    for i in range(len(temp)):
        if temp[i] == '783':
            temp[i] = label[count][0]
            count += 1
    data.annotations.description = temp

    data.save(file_path + name + '.raw.fif', overwrite=True)`

**Comment by anishmrao** [comment]
I converted the data using the above code but encounter the following error when training the model:
`ValueError: No stim channels found. Consider specifying them manually using the 'stim_channel' parameter.`

Please advise on how to preprocess the data from the BCI Competition website (gdf and mat files) to the required mne raw.fif format.
